version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./results:/app/results
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./results:/app/results
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
    command: bash -c "rq worker --url $REDIS_URL default"
